architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
//% if unobfuscated
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    implementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"
//% else
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"
//% end
//% if architectury_api

    // Architectury API. This is optional, and you can comment it out if you don't need it.
//% if unobfuscated
    implementation "%ARCHITECTURY_GROUP%:architectury-fabric:$rootProject.architectury_api_version"
//% else
    modImplementation "%ARCHITECTURY_GROUP%:architectury-fabric:$rootProject.architectury_api_version"
//% end
//% end

//% if unobfuscated
    compileOnly(project(path: ':common')) { transitive = false }
//% else
    compileOnly(project(path: ':common', configuration: 'namedElements')) { transitive = false }
//% end
}
